# Generated by Django 5.2.14 on 2026-05-25 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0005_rename_semestre_cuatrimestre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignatura',
            name='curso',
            field=models.IntegerField(choices=[(1, '1º Curso'), (2, '2º Curso'), (3, '3º Curso'), (4, '4º Curso'), (5, '5º Curso')]),
        ),
        migrations.AlterField(
            model_name='asignatura',
            name='es_electiva',
            field=models.BooleanField(default=False, help_text='Las asignaturas electivas pueden compartir franja horaria con otras electivas del mismo curso y cuatrimestre.', verbose_name='Es electiva'),
        ),
        migrations.AlterField(
            model_name='titulacion',
            name='codigo',
            field=models.CharField(max_length=10, verbose_name='Código'),
        ),
    ]
